### ISSUE TITLE
Memory leak when using listbox

### ISSUE THREAD

**Issue by RustemGimazetdinov** [Actipro/Avalonia-Controls#5] opened 2023-11-10 19:00 UTC
Hi,
Thanks for this wonderful theme library.

I'm facing a memory leak issue when using listboxes.

[Sample](https://github.com/Actipro/Avalonia-Controls/files/13322482/AvaloniaApplication18.zip)

**Comment by boydpatterson** [comment] 2023-11-10 20:09
We're glad to hear you like the theme library! Sorry you're having trouble with a memory leak on a listbox.  Since our native control templates just define custom styles/templates for the listbox, any memory leak would be in the native control itself and you'd need to reach out to the Avalonia UI team for assistance with that.

https://github.com/AvaloniaUI/Avalonia/issues

**Comment by RustemGimazetdinov** [comment] 2023-11-10 20:45
The memory leak only occurs when using your theme. It's not available with the "FluentTheme".

**Comment by boydpatterson** [comment] 2023-11-10 21:04
Well, that's certainly a different situation.  Can you provide steps to reproduce with the sample you previously attached?

**Comment by RustemGimazetdinov** [comment] 2023-11-10 21:17
Each click of the "Next" button creates a new UserControlView. The previous ones are not released, although there should no longer be a reference to them.

**Comment by boydpatterson** [comment] 2023-11-10 21:30
Thank you for the steps. Had to click the button several times to hit the finalizer breakpoint on the view model, but never hit the finalizer breakpoint on the view.  Investigating...

**Comment by boydpatterson** [comment] 2023-11-13 19:45
Thank you, again, for letting us know about this issue and providing the sample to reproduce. We were able to track down some theme logic that was holding references to elements and were able to refactor it to avoid keeping the elements alive. This fix will be in the next maintenance release.

**Closed by boydpatterson** 2023-11-13 19:45 UTC
Labels: bug

**Comment by boydpatterson** [comment] 2023-11-14 21:58
New release is out.
